briefs/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from briefs import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter(trailing_slash=False)
router.register(r'api/brief', views.BriefViewSet, 'api-brief')
router.register(r'api/briefanswers', views.BriefAnswersViewSet, 'api-briefanswers')
router.register(r'api/template', views.BriefTemplateViewSet, 'api-brief-template')

urlpatterns = [
    url(r'^$', login_required(views.BriefList.as_view()), name='briefs'),
    url(r'^answer/(?P<token>[a-f0-9]{32})$', views.BriefAnswer.as_view(), name='brief_answer'),
    url(r'^add/$', login_required(views.BriefDetail.as_view()), name='add_brief'),

    url(r'^(?P<pk>[0-9]+)?$', login_required(views.BriefDetail.as_view()), name='brief_detail'),
    url(r'^template/$', login_required(views.BriefTemplateList.as_view()), name='brieftemplates'),
    url(r'^template/(?P<pk>[0-9]+)?$', login_required(views.BriefTemplateDetail.as_view()), name='brieftemplate_detail'),
    url(r'^template/add/(?P<brief_id>[0-9]+)?$', login_required(views.BriefTemplateDetail.as_view()), name='add_brief_template'),

    url(r'^api/question/(?P<pk>[0-9]+)$', login_required(views.QuestionDetailAPI.as_view()), name='api_question_detail'),
    url(r'^api/questions/$', login_required(views.QuestionsAPI.as_view()), name='api_questions'),
]

urlpatterns += url(r'^api/brief/fields',
                   views.brief_fields_json,
                   name='api-briefs-fields'),

urlpatterns += router.urls

gallant/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import TemplateView
import gallant
import market_analysis
from market_analysis import views
from gallant import views
import allauth.urls
import experiments.urls
from rest_framework.routers import SimpleRouter

router = SimpleRouter(trailing_slash=False)
router.register(r'api/client', views.ClientsAPI, 'api-client')
router.register(r'api/service', views.ServiceAPI, 'api-service')
router.register(r'api/project', views.ProjectsAPI, 'api-project')

urlpatterns = i18n_patterns(

    # ==============
    # FRONTEND EXPERIMENTS

    # Landing page
    url(r'^home', market_analysis.views.LandingPage.as_view(),
        name='landing'),

    url(r'^features', TemplateView.as_view(template_name='market_analysis/features.html'),
        name='features'),

    url(r'^about', TemplateView.as_view(template_name='market_analysis/about.html'),
        name='about'),

    url(r'^contact', TemplateView.as_view(template_name='market_analysis/contact.html'),
        name='contact'),

    url(r'^waiting_list', market_analysis.views.LandingPageSubmit.as_view(),
        name='waiting_list'),

    # Landing page experiments
    url(r'^tool', market_analysis.views.LandingPageTool.as_view(),
        name='tool_test'),

    url(r'^workflow', market_analysis.views.LandingPageFlow.as_view(),
        name='workflow_test'),

    # ==============
    # Rest of Galant
    url(r'^$', gallant.views.Home.as_view(), name='home'),
    url(r'^signup/', gallant.views.SignUpRequest.as_view(), name='signup'),
    # url(r'^contact/', gallant.views.contact, name='contact'),

    url(r'^dashboard/', login_required(gallant.views.UserDashboard.as_view()), name='user_dashboard'),

    url(r'^accounts/', include(allauth.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^quote/', include('quotes.urls')),
    url(r'^briefs/', include('briefs.urls')),
    url(r'^calendar/', include('calendr.urls')),
    url(r'^kanban/', include('kanban.urls')),

    url(r'^clients/$', login_required(gallant.views.ClientList.as_view()), name='clients'),
    url(r'^client/add/$', login_required(gallant.views.ClientCreate.as_view()), name='add_client'),
    url(r'^client/edit/(?P<pk>[0-9]+)$', login_required(gallant.views.ClientUpdate.as_view()), name='edit_client'),
    url(r'^client/delete/(?P<pk>[0-9]+)$', login_required(gallant.views.ClientDelete.as_view()), name='delete_client'),
    url(r'^client/(?P<pk>[0-9]+)?$', login_required(gallant.views.client_detail), name='client_detail'),
    url(r'^client/(?P<pk>[0-9]+)/work/$', login_required(gallant.views.client_work_detail), name='client_work_detail'),
    url(r'^client/(?P<pk>[0-9]+)/money/$', login_required(gallant.views.client_money_detail),
        name='client_money_detail'),

    url(r'^projects/$', login_required(TemplateView.as_view(
        template_name='gallant/projects.html')
    ), name='projects'),
    url(r'^project/add/quote/(?P<quote_id>[0-9]+)?$', login_required(gallant.views.ProjectCreate.as_view()),
        name='add_project'),
    url(r'^project/edit/(?P<pk>[0-9]+)$', login_required(gallant.views.ProjectUpdate.as_view()), name='edit_project'),
    url(r'^project/delete/(?P<pk>[0-9]+)$', login_required(gallant.views.ProjectDelete.as_view()),
        name='delete_project'),
    url(r'^project/(?P<pk>[0-9]+)?$', login_required(gallant.views.project_detail), name='project_detail'),

    url(r'^project/(?P<project_id>[0-9]+)/service/add/$', login_required(gallant.views.ServiceCreate.as_view()),
        name='add_service'),
    url(r'^project/(?P<project_id>[0-9]+)/service/edit/(?P<pk>[0-9]+)$',
        login_required(gallant.views.ServiceUpdate.as_view()), name='edit_service'),
    url(r'^project/(?P<project_id>[0-9]+)/service/(?P<pk>[0-9]+)?$', login_required(gallant.views.service_detail),
        name='service_detail'),

    url(r'^api/service/(?P<pk>[0-9]+)$', gallant.views.ServiceDetailAPI.as_view(),
        name='api_service_detail'),
    url(r'^api/project/(?P<pk>[0-9]+)$', login_required(gallant.views.ProjectDetailAPI.as_view()),
        name='api_project_detail'),
    url(r'^api/client/(?P<pk>[0-9]+)$', login_required(gallant.views.ClientDetailAPI.as_view()),
        name='api_client_detail'),
    url(r'^api/note/(?P<pk>[0-9]+)$', login_required(gallant.views.NoteDetailAPI.as_view()), name='api_note_detail'),
    url(r'^api/users/?$', login_required(gallant.views.UsersAPI.as_view()), name='api_users'),
    url(r'^api/settings/(?P<pk>[0-9]+)$', login_required(gallant.views.UserSettingsAPI.as_view()), name='api_user_settings'),

    url(r'^register/(?P<pk>[0-9]+)', gallant.views.Register.as_view(), name='register'),
    url(r'^account/add/', login_required(gallant.views.AccountAdd.as_view()), name='add_account'),
    url(r'^account/reset/', login_required(gallant.views.PasswordReset.as_view()), name='reset_password'),
    url(r'^feedback/', gallant.views.SubmitFeedback.as_view(), name='feedback'),
)

urlpatterns += patterns('',
                        url(r'^experiments/', include(experiments.urls)),
                        )

urlpatterns += url(r'^api/client/fields',
                   gallant.views.client_fields_json,
                   name='api-client-fields'),

urlpatterns += url(r'^api/project/fields',
                   gallant.views.project_fields_json,
                   name='api-project-fields'),

urlpatterns += url(r'^api/service/fields',
                   gallant.views.service_fields_json,
                   name='api-service-fields'),

urlpatterns += router.urls

briefs/models.py
from uuid import uuid4
from django.conf import settings
from django.db import models as m
from django.db import transaction
from gallant import models as g
from gallant.models import PolyUserModelManager, UserModelManager
from quotes import models as q
from gallant import fields as gf
from jsonfield.fields import JSONField
from gallant import utils


class Question(g.PolyUserModel):
    """
    A brief has Questions that need to be answered.
    """
    question = gf.ULCharField()
    help_text = gf.ULCharField()
    index = m.IntegerField(default=0)

    class Meta:
        permissions = (
            ('view_question', 'View question'),
        )

    objects = PolyUserModelManager()

# guardian uses django's default add / change / delete perms and doesn't play well
# with polymorphic classes, so this manual approach is necessary for subclasses
def _get_question_perms(new_perms):
    return (
        new_perms,
        ('add_question', 'Can add question'),
        ('change_question', 'Can change question'),
        ('delete_question', 'Can delete question'),
        ('view_question', 'View question'),
    )


class TextQuestion(Question):
    """
    Long Answer Question
    """
    is_long_answer = m.BooleanField(default=False)

    class Meta:
        permissions = _get_question_perms(('view_textquestion', 'View textquestion'))

    objects = PolyUserModelManager()


class MultipleChoiceQuestion(Question):
    """
    Multiple Choice Question. We can set it up so the user has to select only one option or can optionally
    select more than one.
    The choices field is a list field where the options for the question are stored.
    """
    can_select_multiple = m.BooleanField(default=False)
    choices = gf.ULTextArrayField()

    class Meta:
        permissions = _get_question_perms(('view_multiplechoicequestion', 'View multiplechoicequestion'))

    objects = PolyUserModelManager()


class ImageQuestion(MultipleChoiceQuestion):
    """
    ImageQuestion is a Multiple Choice Questions that allows the user to select among images.
    """
    # TODO: First finish MultipleChoiceQuestion then continue with ImageQuestions.

    class Meta:
        permissions = _get_question_perms(('view_imagequestion', 'View imagequestion'))

    objects = PolyUserModelManager()


class Image(g.UserModel):
    """
    Image for ImageQuestions.
    """
    # TODO: We should analyze the best place for Image model to be located in.


class BriefStatus(gf.ChoiceEnum):
    Draft = 0
    Not_Sent = 1
    Sent = 2
    Viewed = 3
    Answered = 4
    Rejected = 5


class Brief(g.UserModel):
    """
    A questionnaire that will allow a user to know more about Client needs.
    """
    name = m.CharField(max_length=512, default='New Brief')
    title = gf.ULCharField(max_length=255, help_text='Brief title.')
    greeting = gf.ULCharField(max_length=2000, help_text='Greeting text.', blank=True)
    status = m.CharField(max_length=2, choices=BriefStatus.choices(), default=BriefStatus.Draft.value)
    token = m.UUIDField(default=uuid4, editable=False, unique=True)

    modified = m.DateTimeField(auto_now=True)

    questions = m.ManyToManyField(Question)
    language = m.CharField(max_length=7, null=True, choices=settings.LANGUAGES,
                           help_text='Language of brief, or null for template.')

    client = m.ForeignKey(g.Client, null=True)
    quote = m.ForeignKey(q.Quote, null=True)

    def get_languages(self):
        language_set = set()
        language_set.update(self.title.keys())
        for q in list(self.questions.all_for(self.user, 'view_question')):
            if q is not None:
                language_set.update(q.question.keys())

        return language_set

    def __unicode__(self):
        return self.name

    class Meta:
        permissions = (
            ('view_brief', 'View brief'),
        )

    objects = UserModelManager()

    def soft_delete(self, deleted_by_parent=False):
        with transaction.atomic():
            for question in self.questions.all_for(self.user, 'change_question'):
                question.soft_delete(deleted_by_parent=True)

            super(Brief, self).soft_delete(deleted_by_parent)


class BriefTemplate(g.UserModel):
    """
    A Brief Template to be reused on other clients.
    """
    brief = m.ForeignKey(Brief)

    def language_list(self):
        return [(c, utils.LANG_DICT[c]) for c in self.brief.get_languages() if c in utils.LANG_DICT]

    class Meta:
        permissions = (
            ('view_brieftemplate', 'View brieftemplate'),
        )

    objects = UserModelManager()

    def soft_delete(self, deleted_by_parent=False):
        with transaction.atomic():
            if self.brief.client_id is None:
                self.brief.soft_delete(deleted_by_parent=True)

            super(BriefTemplate, self).soft_delete(deleted_by_parent)


class Answer(g.PolyUserModel):
    question = m.ForeignKey(Question)

    class Meta:
        permissions = (
            ('view_answer', 'View answer'),
        )

    objects = PolyUserModelManager()


# see _get_question_perms()
def _get_answer_perms(new_perms):
    return (
        new_perms,
        ('add_answer', 'Can add answer'),
        ('change_answer', 'Can change answer'),
        ('delete_answer', 'Can delete answer'),
        ('view_answer', 'View answer'),
    )


class TextAnswer(Answer):
    answer = m.CharField(max_length=3000)
    class Meta:
        permissions = _get_answer_perms(('view_textanswer', 'View textanswer'))

    objects = PolyUserModelManager()


class MultipleChoiceAnswer(Answer):
    # a list of choice indexes corresponding to the quesion's choice list
    choices = JSONField()

    @property
    def answer(self):
        if type(self.question) is MultipleChoiceQuestion:
            if self.question.can_select_multiple:
                return [self.question.choices[c] for c in self.choices]
            else:
                return self.question.choices[self.choices[0]]

    class Meta:
        permissions = _get_answer_perms(('view_multiplechoiceanswer', 'View multiplechoiceanswer'))

    objects = PolyUserModelManager()


class BriefAnswers(g.UserModel):
    brief = m.ForeignKey(Brief)
    answers = m.ManyToManyField(Answer)

    created = m.DateTimeField(auto_now_add=True)

    class Meta:
        permissions = (
            ('view_briefanswers', 'View briefanswers'),
        )

    objects = UserModelManager()

gallant/forms/client.py
from django.utils.translation import get_language
from gallant import models as g
from user import UserModelNgForm


class ClientForm(UserModelNgForm):
    class Meta:
        model = g.Client
        fields = ['name', 'email', 'company',
                  'status', 'language', 'referred_by']

    def __init__(self, *args, **kwargs):
        kwargs.update(prefix='client')
        super(ClientForm, self).__init__(*args, **kwargs)
        self.initial['language'] = get_language()

gallant/forms/note.py
from django import forms
from gallant import models as g
from user import UserModelNgForm


class NoteForm(UserModelNgForm):
    class Meta:
        model = g.Note
        fields = ['text']

    def __init__(self, *args, **kwargs):
        kwargs.update(prefix='note')
        super(NoteForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget = forms.Textarea(attrs={'rows': 3})
        self.fields['text'].label = 'Notes are not accessible to clients'
        self.fields['text'].help_text = ''

gallant/forms/project.py
from django import forms
from django.db.models import Count
from gallant import models as g
from quotes import models as q
from user import UserModelForm


class ProjectForm(UserModelForm):

    class Meta:
        model = g.Project
        fields = ['name', 'status']

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['notes'] = forms.CharField(
            widget=forms.Textarea(attrs={'rows': 5}), required=False)


class ProjectOnlyForm(UserModelForm):

    class Meta:
        model = g.Project
        fields = ['name', 'status']

    def __init__(self, *args, **kwargs):
        super(ProjectOnlyForm, self).__init__(*args, **kwargs)

        if self.instance.id is not None:
            quote_set_a = self.instance.quote_set.all_for(self.user)
            quote_set_b = []

            if len(quote_set_a) > 0:
                client = quote_set_a[0].client
                quote_set_b = q.Quote.objects.all_for(
                    self.user).annotate(projects_count=Count('projects')).filter(
                    projects_count=0, status=5, client_id=client.id)
            else:
                quote_set_b = q.Quote.objects.all_for(
                    self.user).annotate(projects_count=Count('projects')).filter(
                    projects_count=0, status=5)

            linked_quotes = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple({'checked': True}),
                                                           queryset=quote_set_a)

            available_quotes = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple({'checked': False}),
                                                              queryset=quote_set_b, required=False)

            if len(linked_quotes.queryset) > 0:
                self.fields['linked_quotes'] = linked_quotes

            if len(available_quotes.queryset) > 0:
                self.fields['available_quotes'] = available_quotes

gallant/forms/service.py
from django import forms
from gallant import models as g
from user import UserModelForm


class ServiceForm(UserModelForm):
    class Meta:
        model = g.Service
        fields = ['name', 'description', 'cost', 'time']

    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)
        self.fields['notes'] = forms.CharField(
            widget=forms.Textarea(attrs={'rows': 5}), required=False)


class ServiceOnlyForm(UserModelForm):
    class Meta:
        model = g.Service
        fields = ['name', 'description', 'cost', 'time']

gallant/views/misc.py
from gallant import serializers
from gallant import models as g
from gallant.utils import GallantObjectPermissions
from rest_framework import generics


class NoteDetailAPI(generics.RetrieveUpdateAPIView):
    model = g.Note
    serializer_class = serializers.NoteSerializer
    permission_classes = [
        GallantObjectPermissions
    ]

    def get_queryset(self):
        return self.model.objects.all_for(self.request.user)

gallant/templates/gallant/add_note.html
{% load i18n %}

<form class="mt" action="" method="post">
    {% csrf_token %}
    <div class="form-group mb-0">
        {{ form.as_div }}
        {% if form.is_bound and not form.is_valid %}
            <div class="form-group has-error">
                <span class="help-block">{{ form.text.errors.as_text }}</span>
            </div>
        {% endif %}
    </div>
    <div class="btn-toolbar">
        <button id="note_add" type="submit" class="btn btn-success pull-right">{% trans "Add Note" %}</button>
    </div>
</form>

gallant/templates/gallant/base_form.html
{% extends "base_body.html" %}
{% load staticfiles bootstrap i18n %}

{% block section_title %}
    {{ title }}
{% endblock %}

{% block content %}
    <section class="widget">

        <form id="main_form" name="{{ form.form_name }}" class="form" method="post" action="">
            <div class="widget-body">

                {% block form_quick_actions %}
                {% endblock %}

                {% block form_help_text %}
                    {% if help_text %}
                        <p class="title">
                            <i>
                                {{ help_text }}
                            </i>
                        </p>
                    {% endif %}
                {% endblock %}

                {% csrf_token %}
                {% block pre_form %}{% endblock %}
                {% block form_body %}
                    {{ form|bootstrap }}
                {% endblock %}
                {% block post_form %}{% endblock %}

            </div>

            <div class="form-actions">
                {% block form_actions %}
                    <button id="create_submit" class="btn btn-inverse" type="submit">
                        {{ submit_text|default:_("Save") }}
                    </button>
                {% endblock %}
            </div>
        </form>

    </section>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script>
        jQuery(document).ready(function ($) {
            // Save form contents
            $('.form').each(function () {
                $(this).data('serialize', $(this).serialize());
            });

            var confirmOnPageExit = function (e) {
                var modified = false;
                $('.form').each(function () {
                    if ($(this).serialize() != $(this).data('serialize')) {
                        modified = true;
                        return false;
                    }
                });

                $('.ultext_target, .ultext_array_target').each(function () {
                    if ($(this).val() != $(this).data('val')) {
                        modified = true;
                        return false;
                    }
                });

                if (!modified) {
                    return null;
                }

                // If we haven't been passed the event get the window.event
                e = e || window.event;

                var message = 'You have unsaved changes. If you leave this page they will be lost.';

                // For IE6-8 and Firefox prior to version 4
                if (e) {
                    e.returnValue = message;
                }

                // For Chrome, Safari, IE8+ and Opera 12+
                return message;
            };

            // Turn it on - assign the function that returns the string
            window.onbeforeunload = confirmOnPageExit;

            $('.form').submit(function () {
                window.onbeforeunload = null;
            });
        });
    </script>
{% endblock %}

gallant/templates/gallant/client_money_detail.html
{% extends "../templates/gallant/client_detail.html" %}
{% load bootstrap i18n gallant_tags staticfiles static djng_tags %}

{% block page_title %}
    {{ object.name }} - <span class="fw-semi-bold">{% trans 'Payments' %}</span>
{% endblock %}

{% block content %}

    {% block client_detail %}
    {% endblock %}

    {% block main_client_data %}
        <div class="projects" ng-controller="glClientPaymentController" client_id="{{ object.id }}">
            <div class="row">
                <div class="col-lg-10 col-md-10 col-sm-9 col-xs-9">
                </div>
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-3">
                    <button class="btn btn-default btn-success pull-right" ng-click="openEditModal()">
                        <span class="glyphicon glyphicon-plus"></span> Add Payment
                    </button>
                    <br/>
                    <br/>
                    <br/>
                </div>
            </div>
            <div gl-payments client_id="{{ object.id }}" open-edit-modal="openEditModal" payments="payments" class="table table-striped">
            </div>
        </div>
    {% endblock %}

    {% block client_alerts %}
        {{ block.super }}
    {% endblock %}

    {% block client_notes %}
    {% endblock %}

{% endblock %}

gallant/templates/gallant/contact_info.html
{% load i18n %}

{% if object.phone_number %}
<p><span class="detail_title">{% trans "Phone" %}:</span> {{ object.phone_number }}</p>
<br>
{% endif %}

<p><span class="detail_title">{% trans "Address" %}:</span></p>

{% if object.address %}
<p>{{ object.address }}<br/>
{% endif %}

{% if object.address_2 %}
    {{ object.address_2 }}<br/>
{% endif %}

{% if object.city %}
{{ object.city}}{% if object.city %},{% endif %}
{% endif %}

{% if object.state %}
{{ object.state }}
{% endif %}

{% if object.zip %}
{{ object.zip }}<br/>
{% endif %}

{{ object.get_country_display }}

gallant/templates/gallant/form.html
{% extends "base.html" %}
{% load bootstrap %}

{# Disable unneeded JS scripts to prevent synchronous execution when called from $.get() #}
{% block css %}{% endblock %}
{% block scripts %}{% endblock %}

{% block body %}
<div class="col-lg-12">
    <form id="form" class="form" method="post">
        {% csrf_token %}
        {% block pre_form %}{% endblock %}
        {{ form|bootstrap }}
        {% block post_form %}{% endblock %}

        <div class="form-actions">
            {% block form_actions %}
                <button id="create_submit" class="btn btn-default btn-submit" type="submit">
                    {{ submit_text|default:_("Save") }}
                </button>
            {% endblock %}
        </div>
    </form>
</div>
{% endblock %}

gallant/templates/gallant/project_detail.html
{% extends "base_body.html" %}
{% load bootstrap i18n gallant_tags static %}

{% block page_title %}
    {% trans "Project" %} - <span class="fw-semi-bold">Dashboard</span>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static "djng/js/django-angular.min.js" %}"></script>
    <script src="{% static "js/ng-sortable.js" %}"></script>
    <script src="{% static "js/angular-animate.js" %}"></script>
{% endblock %}

{% block project_scripts %}
    {{ block.super }}
    {% if DEBUG %}
        <script src="{% static "js/quotes.js" %}"></script>
        <script src="{% static "js/kanban.js" %}"></script>
    {% endif %}
{% endblock %}

{% block project_css %}
    {{ block.super }}

    <link rel="stylesheet" href="{% static "css/ng-sortable.style.min.css" %}">
    <link rel="stylesheet" href="{% static "css/ng-sortable.min.css" %}">

{% endblock %}

{% block extra_wrapper_attrs %} ng-app="glProjectDetail" {% endblock %}

{% block content %}
    <div gl-alerts></div>

    <div ng-controller="glProjectDetailController" ng-init="init('{% url 'service_detail' object.id %}', {{ object.id }}, '{% firstof language LANGUAGE_CODE %}')">

        <div class="row">
            <div class="col-md-12">
                {% block main_client_data %}
                    <section class="widget">
                        <div class="widget-body">
                            <div class="widget-top-overflow text-white">
                                <div class="height-100 overflow-hidden">
                                    <img class="img-responsive" src="{% static "img/galant/background.jpg" %}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-5 text-center">
                                    <div class="post-user post-user-profile">
                                        <h4 class="fw-normal">{{ object.name }}</h4>
                                        <span class="label label-danger"> {{ object.get_status_display }} </span>

                                        {% if object.client %}
                                            <ul class="contacts">
                                                <li>
                                                    <i class="fa fa-building fa-fw mr-xs"></i><a href="{% url 'client_detail' object.client.id %}"> {{ object.client.name }}</a>
                                                </li>
                                            </ul>
                                        {% endif %}

                                    </div>
                                </div>
                                <div class="col-sm-7">

                                    <div gl-add-modal open-fn="editProject" title="Edit Project" modal-instance="modalInstance">
                                        <div gl-project-add on-success="projectSaved" project="projectSafe" language="{% firstof language LANGUAGE_CODE %}"></div>
                                    </div>

                                    <div class="stats-row stats-row-profile mt text-right">
                                        <div class="stat-item">
                                            <p class="value">{% get_project_services_count request object  %}</p>
                                            <h5 class="name">Deliverables</h5>
                                        </div>
                                        <div class="stat-item">
                                            <p class="value">{% get_project_advance request object %}</p>
                                            <h5 class="name">Advance</h5>
                                        </div>
                                    </div>
                                    <p class="text-right mt-lg">
                                        <button id="section_edit" type="button" class="btn btn-warning btn-sm mt" aria-label="Edit"
                                                ng-click="editProjectSafe()">
                                            &nbsp;Edit
                                            &nbsp;&nbsp;<i class="glyphicon glyphicon-edit"/></i>&nbsp;
                                        </button>
                                        <a href="{% url 'delete_project' object.id %}" class="delete_button" title="{% trans "Delete" %}" onclick="return confirm('{% trans "Are you sure? This will also delete all links between the project and its linked quotes." %}')"> 
                                            <button id="section_delete" type="button" class="btn btn-danger btn-sm mt" aria-label="Delete"> 
                                                &nbsp;Delete
                                                &nbsp;&nbsp;<i class="glyphicon glyphicon-trash"/></i>&nbsp;
                                            </button>
                                        </a> 
                                    </p>
                                </div>
                            </div>
                        </div>
                    </section>
                    <span gl-client-work-chart client-id="{{ object.id }}" add-brief-url='{% url 'add_brief' %}' language='{% firstof language LANGUAGE_CODE %}'>
                    </span>
                    <span gl-client-money-chart client-id="{{ object.id }}" add-quote-url='{% url 'add_quote' %}' language='{% firstof language LANGUAGE_CODE %}'>
                    </span>
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <h2 class="section_title">Deliverables</h2>
            </div>
            <div class="col-sm-6">
                <div gl-add-modal open-fn="editDeliverable" title="Edit Deliverable" modal-instance="modalInstance">
                    <div gl-deliverable-add deliverable="object" project="project"
                         on-success="projectSaved" language="{% firstof language LANGUAGE_CODE %}"></div>
                </div>
                <button type="button" class="btn btn-success pull-right" ng-click="editDeliverable()">
                    <span class="glyphicon glyphicon-plus"></span>
                    Add Deliverable
                </button>
            </div>
        </div>

        <br/>
        <div ng-include src="'{% static "gallant/html/gl_service_board.html" %}'">
        </div>

    </div>

    <div>


        {% if brief in briefs %}

            <hr>
            <div id="briefs">
                <h2 class="section_title">
                    {% trans "Project Briefs" %}
                </h2>

                <hr>

                {% objects_for object.quote.brief_set as briefs %}
                {% for brief in briefs %}
                    <div class="brief_link">
                        <a href="{% url 'brief_detail' brief.id %}?project_id={{ object.id }}">{{ brief }} </a>&mdash;
                        {{ brief.modified|date:'Y-m-d H:i' }}
                    </div>
                {% endfor %}
            </div>
            <hr>

        {% endif %}

        <div id="notes">

            <h2 class="section_title">
                {% trans "Project Notes" %}
            </h2>

            <hr>

            {% objects_for object.notes as notes %}
            {% for item in notes %}
                {% include "gallant/note.html" %}
            {% endfor %}
            <div>
                {% include "gallant/add_note.html" %}
            </div>
        </div>
    </div>
{% endblock %}